### ISSUE TITLE
Error when using connection pool

### ISSUE THREAD

**Issue by hgani** [phawk/dalli-ui#4]
Hi,

As soon as I use connection pool (as instructed in https://github.com/mperham/dalli under "Multithreading and Rails" section), I can't open my dalli-ui page anymore.

Here's what the server log (on Heroku) says:

2015-09-02T11:44:10.059122+00:00 app[web.1]: undefined method `stats' for #<ConnectionPool:0x007fa9b071c940> in /app/vendor/bundle/ruby/2.2.0/gems/dalli-ui-0.1.2/app/controllers/dalli/ui/cache_controller.rb:9:in`index'
2015-09-02T11:44:10.059133+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2015-09-02T11:44:10.059134+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in`process_action'
2015-09-02T11:44:10.059136+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
2015-09-02T11:44:10.059137+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in`block in process_action'
2015-09-02T11:44:10.059138+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
2015-09-02T11:44:10.059140+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in`call'
2015-09-02T11:44:10.059141+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
2015-09-02T11:44:10.059143+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in`call'
2015-09-02T11:44:10.059144+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
2015-09-02T11:44:10.059145+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in`run_callbacks'
2015-09-02T11:44:10.059147+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
2015-09-02T11:44:10.059148+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in`process_action'
2015-09-02T11:44:10.059150+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'

Thanks

**Comment by phawk** [comment]
Hi @hgani sorry this gem hasn’t seen much production use outside of my usecase where I am not running a connection pool, just a single memcached instance. Either send a pull request to support multiple memcached instances or I will get round to it at some point, not sure when that might be though, sorry!

**Comment by hgani** [comment]
@phawk no worries.

I am new to memcached so I won't be able to help much. I'll look around for alternative gems. Thanks.

**Comment by MoKuH** [comment]
@hgani 
fixed here if you want https://github.com/MoKuH/dalli-ui

@phawk still maintaining the repo ? PR welcome ?
